apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opswingman-staging

resources:
  - ../../base

images:
  - name: opswingman/backend
    newName: ghcr.io/opswingman/backend
    newTag: staging-latest

patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
