"""
Workflow State and Execution Context Models (Phase 2 - Deliverables D-08, D-09).
"""

import uuid
from enum import Enum
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class WorkflowState(str, Enum):
    """Lifecycle states of an operational workflow execution."""
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    WAITING_FOR_TOOL = "WAITING_FOR_TOOL"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    RETRYING = "RETRYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class WorkflowStepRecord(BaseModel):
    """Log entry for an executed workflow step or tool interaction."""
    step_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:8])
    step_name: str
    state: WorkflowState
    tool_name: Optional[str] = None
    input_payload: Optional[Dict[str, Any]] = None
    output_payload: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class StructuredAction(BaseModel):
    """Structured proposal generated by the agent before execution."""
    action: str = Field(..., description="Action name, e.g. 'track_shipment', 'cancel_order', 'send_message'")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Action parameters")
    reason: str = Field(..., description="Business justification for the action")
    risk: str = Field(default="LOW", description="LOW, MEDIUM, or HIGH")
    requires_approval: bool = Field(default=False, description="Whether approval gate is required")


class WorkflowRunRecord(BaseModel):
    """Complete checkpoint record of a workflow run."""
    workflow_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    run_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    workflow_type: str = Field(default="order_operations")
    state: WorkflowState = Field(default=WorkflowState.CREATED)
    customer_id: Optional[str] = None
    order_id: Optional[str] = None
    event_id: Optional[str] = None
    input_text: str = Field(default="")
    intent: Optional[str] = None
    extracted_entities: Dict[str, Any] = Field(default_factory=dict)
    steps: List[WorkflowStepRecord] = Field(default_factory=list)
    proposed_actions: List[StructuredAction] = Field(default_factory=list)
    final_response: Optional[str] = None
    error: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
