"""Seed Knowledge Documents for OpsWingman RAG System (Phase 3 - Deliverable D-10).

Seeds realistic Indian SMB operational policies, SLAs, and SOPs into PostgreSQL/pgvector.
"""

from typing import Any, Dict, List
from sqlalchemy.orm import Session

from backend.rag.schemas import DocumentIngestRequest
from backend.rag.service import RAGService
from database.models.enums import DocumentType

SEED_DOCUMENTS: List[Dict[str, Any]] = [
    {
        "document_id": "POL-SHP-001",
        "title": "POL-SHP-001: Shipping, Logistics & Delivery SLA Policy",
        "doc_type": DocumentType.POLICY,
        "source": "policies/shipping_sla_v1.md",
        "version": "1.0.0",
        "content": """# Shipping, Logistics & Delivery SLA Policy (POL-SHP-001)

## 1. Standard Delivery Timeframes
All confirmed customer orders are dispatched within 24-48 business hours via primary logistics partners (Delhivery, BlueDart, EcomExpress). Standard surface transit takes 3-5 business days depending on delivery pincode and hub clearance.

## 2. Transit Delays & Proactive Notifications
If a shipment is stationary in transit hub or marked DELAYED for more than 48 hours without location advancement:
- Automatic tracking update notification must be dispatched to the customer.
- An internal operational support ticket (Category: ORDER_DELAY, Priority: HIGH) must be opened to coordinate with the logistics carrier.

## 3. Delivery Confirmation & Proof of Delivery
A shipment is marked DELIVERED upon digital OTP confirmation or physical signature receipt. If customer disputes delivery, an investigation must be initiated within 24 hours.""",
        "metadata": {"policy_id": "POL-SHP-001", "effective_date": "2026-01-01", "department": "Logistics"},
    },
    {
        "document_id": "POL-CAN-001",
        "title": "POL-CAN-001: Order Cancellation & Modification Policy",
        "doc_type": DocumentType.POLICY,
        "source": "policies/cancellation_v1.md",
        "version": "1.0.0",
        "content": """# Order Cancellation & Modification Policy (POL-CAN-001)

## 1. Eligible Cancellation Windows
Customers may cancel an order directly while it remains in PENDING or CONFIRMED state prior to warehouse packaging and shipment manifest generation.

## 2. Disallowed Post-Dispatch Cancellations
Once an order has transitioned to PROCESSING, SHIPPED, IN_TRANSIT, or DELIVERED status:
- Direct order cancellation is strictly disallowed under company policy.
- Customer must be informed that the parcel is in transit and that a Return / Replacement request can be initiated following delivery receipt.

## 3. High-Value Order Cancellation Approval Gate
Cancellation of active orders with total value exceeding INR 5,000.00 is classified as HIGH risk and strictly requires human supervisor approval before database execution.""",
        "metadata": {"policy_id": "POL-CAN-001", "effective_date": "2026-01-01", "department": "Order Operations"},
    },
    {
        "document_id": "POL-REF-001",
        "title": "POL-REF-001: Refund, Payment & Dispute Policy",
        "doc_type": DocumentType.POLICY,
        "source": "policies/refund_v1.md",
        "version": "1.0.0",
        "content": """# Refund, Payment & Dispute Settlement Policy (POL-REF-001)

## 1. Refund Eligibility Prerequisites
Refunds may only be issued against captured, successful payments (PaymentStatus: SUCCESSFUL). Orders with failed, initiated, or uncaptured payment attempts are not eligible for cash refunds.

## 2. Low-Value vs High-Value Refund Thresholds
- Low-Value Refunds (<= INR 2,000.00): Eligible for automated operational processing upon verified order cancellation or return confirmation.
- High-Value Refunds (> INR 2,000.00): Classified as HIGH risk financial transactions. Strictly requires human operations supervisor approval before refund initiation.

## 3. Settlement Timeline
Approved refunds are credited to the original payment source (UPI VPA, NetBanking, Card) within 5-7 business banking days with gateway reference tracking.""",
        "metadata": {"policy_id": "POL-REF-001", "effective_date": "2026-01-01", "department": "Finance & Accounting"},
    },
    {
        "document_id": "SOP-COMM-001",
        "title": "SOP-COMM-001: Customer Support Communication Protocols",
        "doc_type": DocumentType.SOP,
        "source": "sops/customer_messaging_v1.md",
        "version": "1.0.0",
        "content": """# Customer Support Communication Protocols (SOP-COMM-001)

## 1. Professional Tone & Grounding
All customer messages generated by automated agents or human representatives must be professional, courteous, clear, and strictly grounded in verifiable system order state and active policies.

## 2. Reference Identifiers
Every dispatched customer communication must explicitly cite:
- Order Number (ORD-YYYYMMDD-XXXXXX)
- Tracking Number and Carrier Name (for shipment inquiries)
- Resolution SLA or Next Action Steps

## 3. Communication Channels
Primary outbound channel is verified Email, followed by transactional WhatsApp/SMS for real-time delivery alerts.""",
        "metadata": {"sop_id": "SOP-COMM-001", "department": "Customer Experience"},
    },
    {
        "document_id": "SOP-ESC-001",
        "title": "SOP-ESC-001: Exception Escalation & Approval Routing SOP",
        "doc_type": DocumentType.SOP,
        "source": "sops/escalation_v1.md",
        "version": "1.0.0",
        "content": """# Exception Escalation & Approval Routing SOP (SOP-ESC-001)

## 1. Mandatory Human Approval Triggers
Workflows must immediately pause execution and route a formal request to the Human Approval Queue when:
- Proposed action has risk tier HIGH (e.g., order cancellation, high-value refund > INR 2,000).
- Order value exceeds supervisor threshold (> INR 5,000).
- Customer indicates legal grievance or payment chargeback threat.

## 2. Operator Review Contract
Human operators must review the proposed action parameters, policy decision rationale, and attached knowledge citations before granting or denying approval. Once decided, the workflow resumes deterministically.""",
        "metadata": {"sop_id": "SOP-ESC-001", "department": "Operations Management"},
    },
]


def seed_default_knowledge(session: Session) -> int:
    """Ingests the canonical knowledge documents into the database and returns count."""
    service = RAGService(session)
    count = 0
    for item in SEED_DOCUMENTS:
        req = DocumentIngestRequest(
            document_id=item["document_id"],
            title=item["title"],
            doc_type=item["doc_type"],
            source=item["source"],
            version=item["version"],
            content=item["content"],
            metadata=item["metadata"],
        )
        service.ingest_document(req)
        count += 1
    return count


def seed_knowledge_documents(session: Session) -> List[Any]:
    """Compatibility alias for seeding knowledge documents."""
    service = RAGService(session)
    ingested = []
    for item in SEED_DOCUMENTS:
        req = DocumentIngestRequest(
            document_id=item["document_id"],
            title=item["title"],
            doc_type=item["doc_type"],
            source=item["source"],
            version=item["version"],
            content=item["content"],
            metadata=item["metadata"],
        )
        doc = service.ingest_document(req)
        ingested.append(doc)
    return ingested
